#pragma config(Sensor, S1,     redButton,      sensorEV3_Touch)
#pragma config(Sensor, S4,     sensorFront,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorLeft,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define sensorFront S4

#include "config.c"
#include "position.c"
#include "movement.c"
#include "sonar.c"

task displayPos() {
	struct PosData pos;
	while (false) {
		getPosition(&pos);
		displayBigTextLine(1, "X : %6.2f", pos.x);
		displayBigTextLine(3, "Y : %6.2f", pos.y);
		displayBigTextLine(5, "O : %6.2f", pos.orientation);
		writeDebugStreamLine("X:%5.1f Y:%5.1f O:%5.1f", pos.x, pos.y, pos.orientation);
		wait1Msec(50);
	}
}

task emergencyStop() {
	while (SensorValue[redButton] == 0) { wait1Msec(20); }
	stopAllTasks();
}


task main()
{
	datalogClear();
  initConfig(AVERELL);
  initPosition(true);
  while (SensorValue[redButton] == 1) { wait1Msec(20); }
  wait1Msec(500);
  startTask(displayPos);
  startTask(avoidObstacles);
  startTask(emergencyStop);
  suspendTask(avoidObstacles);

  moveTo_forward(300,0);
  moveTo_forward(200,-500);
  wait10Msec(50);
  resumeTask(avoidObstacles);
  moveTo_forward(0,-400);
  moveTo_forward(350,0);

  moveTo_forward(600,-100);

  while (getMovementState() != NOMVT) {wait1Msec(20);}
  stopAllTasks();
}
