#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     redButton,      sensorTouch)
#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Sensor, S4,     ,               sensorSONAR)
#pragma config(Motor,  mtr_Matrix_S1_1, motorD,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorLeft,     tmotorMatrix, PIDControl, driveLeft)
#pragma config(Motor,  mtr_Matrix_S1_3, motorRight,    tmotorMatrix, PIDControl, driveRight)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define sensorFront S4
#define sensorFront2 S3

#include "config.c"
#include "position.c"
#include "movement.c"
#include "sonar.c"

task displayPos() {
	struct PosData pos;
	while (true) {
		wait1Msec(200);
		getPosition(&pos);
		displayBigTextLine(1, "X %5.1f", pos.x);
		displayBigTextLine(3, "Y %5.1f", pos.y);
		displayBigTextLine(5, "O %5.1f", pos.orientation);
		//writeDebugStreamLine("X:%5.1f Y:%5.1f O:%5.1f", pos.x, pos.y, pos.orientation);
	}
}

task emergencyStop() {
	clearTimer(T3);
	while (SensorValue[redButton] != 1 && time1[T3] < 99000) { wait1Msec(20); }
	stopAllTasks();
}

task main()
{
	datalogClear();
	initConfig(LUCKY);
  initPosition(true);
  while (SensorValue[redButton] == 1) { wait1Msec(20); }
  wait1Msec(500);
 	startTask(displayPos);
  startTask(avoidObstacles);
  startTask(emergencyStop);

  struct PosData pos;
  getPosition(&pos);

  moveTo_forward(1500,0);

  moveTo_forward(1500,-300);
  wait10Msec(100);
  suspendTask(avoidObstacles);

  moveTo_forward(200,-250);
  wait10Msec(25);
  resumeTask(avoidObstacles);

  moveTo_backward(250,-300);

  moveTo_forward(200,150);

  while (getMovementState() != NOMVT) { wait1Msec(20); }
  stopAllTasks();
}
